### PR TITLE
Remove Style for the toastify message fom galene.js put them to galene.css

### PR DESCRIPTION
**Pull request by jjsarton**
In order to have a better color contrast I have also set the color to black and modified a little bit the error background.

### CODE REVIEW

**Comment by jech** [comment]
Is it necessary to define the extra CSS variables rather than putting the colors directly into the style?

**Comment by jjsarton** [comment]
Setting styles within a program or a JavaScript is always a bad idea. If the colours are provided within a css file, it is easyer to adapt the colour, particularly if we try to adapt the colours for particular vision problems, for example if some user are light sensitive (light mode versus dark mode).

**Comment by jech** [comment]
I understand that, and I agree.

What I don't understand is why you first set a bunch of CSS variables:
```
    --toast-warn-bg: linear-gradient(to right, #bdc511, #c2cf01);
    --toast-warn-col: #000;
```
and then you use the variables to set the style:
```
.toastify.warning {
    background: var(--toast-warn-bg);
    color: var(-toast.warn-col);
}
```
Is there a good reason for the indirection, or would it be enough to use the values directly in the style, without defining the variables?

**Comment by jjsarton** [comment]
I have 2 version of galene, one for development and my clone of galene. While transferring the changes,  I have done a mistake, I will correct this on the afternoon.
Concerning the  use of css variable, I will later set 2 color scheme. The main color scheme (light) is noted within 
```
:root {
   --backround: white;
   --color: black;
   ...
}

@media (prefers-color-scheme: dark) {
  --background: black;
  --color: white;
}
```
This allows to have to sets of colors which are used according to the user preferencses (and needs).
If you look at the site waisen-der-medizin.de you will normally have a light color scheme. If the OS is configured for a dark color scheme, the color scheme will be choosed automatically from the browser. You can check the effect with the firefox debugger which offer (sun and moon symbols) to use the ligth eg. dark scheme.

**Comment by jjsarton** [comment]
I have removed the css variable and commited this (4aa52e1).

**Comment by jech** [comment]
Thanks.  Rebased, squashed and applied as c040dd2.  (In the future, I would be grateful if you could rebase and squash yourself before submitting.)

**Comment by jech** [comment]
> I have to learn in order to make my work with github better.

Don't work on the master branch.  Keep your master branch in sync with mine, and create a feature branch for every feature you want to send me:
```
git checkout -b toast-css
```
Put your commits on the `toast-css` branch, not on master.  This way, you can keep your changes while keeping your master branch up to date with mine.

 When you're ready to submit, update your master branch, then rebase your branch over the latest master:
```
git checkout master
git pull
git checkout toast-css
git rebase master
```
Now test that it still works, optionally squash the changes (`git rebase -i master`), and do a pull request for the feature branch.

**Comment by jjsarton** [comment]
Okay I will try to to the job as expected.

**Pull request closed without merging**
