### PR TITLE
Allow scroll bars in input form.

### PR DESCRIPTION
**Pull request by jech**
@takdj, users are complaining that there's no feedback when copy-pasting multi-line text into Galene.  The simple solution is the attached, but perhaps it would be better to have the form expand up to 4 lines or so, and only add the scrollbars when the text doesn't fit in four lines?

Please let me know what you think.

### CODE REVIEW

**Comment by takdj** [comment]
Yes, input form that expand is a really better, I can try and send you the patch later.

**Comment by takdj** [comment]
@jech there is a patch here that you can test if ok for you:
https://lab.nexedi.com/alain.takoudjou/galene/commit/06cdf51a0ce3db1838ea206dd8481139e4d7546b

**Comment by takdj** [comment]
https://lab.nexedi.com/alain.takoudjou/galene/commit/332a7e7a79d5310ca2595e1e6774062ec1e3dcce

**Comment by jech** [comment]
I feel taht this should not require any Javascript code.

**Pull request closed without merging**
