### PR TITLE
Updates on README file

### PR DESCRIPTION
**Pull request by ofrzeta**

### CODE REVIEW

**Comment by jech** [comment]
> Rename README to README.md

Sorry, no.  It is a Github bug that a file's type needs to be encoded in the name, I'm not renaming files to work around their bugs.

> Add note on "presenter" entry

Not at this point: if a clarification is needed, it should appear near the `presenter` entry, not in the heading.

**Comment by ofrzeta** [comment]
Well, I put the note in the place where it says that "all entries are optional" while they are not.

**Comment by jech** [comment]
Ah, I see — they are optional, but you won't be able to login unless you define some user entries.

**Comment by ofrzeta** [comment]
I had user entries so I was able to log in. I had no audio/video controls, though, until I added an empty "presenters" array. Maybe other people are better at understanding this, but for me it was a stumbling block.

**Comment by jech** [comment]
You're right, a clarification is needed.  I'll think it over.

**Comment by jech** [comment]
Superseded by 2ec0c0145812c943fefcebe6906b2607a64ddd23.

**Pull request closed without merging**
