### PR TITLE
GUI translation tool - first dictionnary: en & fr

### PR DESCRIPTION
**Pull request by GayLaurent**
Hello,

I propose a tool to manage translation for GUI.
- json file guiconfig.json (or guiconfig-template.json) allow to define a variable "lang" to select language.
- script [static/translate.js](https://github.com/jech/galene/compare/master...GayLaurent:galene:translate#diff-6da340109542775c63e02f61a1a9d86348175364cc2e624a9cbc1c235641820e) manage json dictionnary
- To translate in HTML: add "lang" in class attribut
- To translate in JavaScript: use "translate_text" function

Thank for this application.

### CODE REVIEW

**Comment by jech** [comment]
Thanks a lot.  Translations of Galene have been requested by a number of users.

However, I have some misgiving with the approach taken here.  First, you're using `sed` in order to generate the translations, which will make porting to Windows challenging (Galene works out of the box on Windows, which is the reason why we're not using a Makefile).  Second, you're patching the prototype of `String`, which makes me somewhat uncomfortable.

What about introducing a new dependency? Are there no standard Javascript libraries that perform internationalisation?

**Comment by dashohoxha** [comment]
> What about introducing a new dependency? Are there no standard Javascript libraries that perform internationalisation?

Do you mean something like this: https://www.localeplanet.com/support/howto-localize-js.html ?

**Comment by jech** [comment]
Not necessarily.  I'm not sure that GNU gettext is the right approach, I suspect one can do better in a language as malleable as JavaScript.

**Comment by GayLaurent** [comment]
Thanks for this return.

In fact, my script "extract_for_translate.sh" is a developper tools. 
It is not intended to be distributed in production.
It's a "one shot" tools : after that translation dictionnary is create, after we'll add new sentence inside manualy.
I have commit it just because i have create it to extract my first dictionnary.

> What about introducing a new dependency? Are there no standard Javascript libraries that perform internationalisation?
In fact, i have create a very simple translation tool, dedicated to Galene.
It's just lightless than import an external library.

my proposal may not be retained for the translation of Galène.
I propose it because it is the one that I quickly put in place for a specific need.
And then, it can give ideas to set up something more perine.

**Pull request closed without merging**
