### PR TITLE
Implement activity detection to the local stream

### PR DESCRIPTION
**Pull request by ineol**
Strangely, on my machine the indicator seem to be slower than for incoming streams.

### CODE REVIEW

**Comment by jech** [comment]
We use different intervals for up and down streams: search for `setStatsInterval`.  Reducing the stats interval for up streams will result in the data rate being averaged over a smaller interval, which might or might not be a problem, and might or might not increase CPU consumption on small devices.

I support your proposal, but I feel it needs some more tweaking.

**Comment by ineol** [comment]
The interval is now only shortened when the activity indicator is enabled. The update rate of the rate display is too fast and it's very distracting.

I'm not so sure how to slow it down. Maybe have `updateStats` accumulate `bytesSent` and have `onstats` clear it after 2s? But that would make the interface more complicated.

**Comment by jech** [comment]
> I'm not so sure how to slow it down. Maybe have updateStats accumulate
> bytesSent and have onstats clear it after 2s? But that would make the interface
> more complicated.

I can see a few solutions.

Let n be 2s/interval.  Have onstats do something like

    if(!track.userdata.rateHistory)
        track.userdata.rateHistory = [];
  track.userdata.rateHistory = track.userdata.rateHistory.append(sample);
  if(track.userdata.rateHistory.length >= n) {
      rate = average(track.userdata.rateHistory);
      track.userdata.rateHistory = [];
  }

We're doing some useless work (we're integrating in updateStats then
summing in onstats), but the interface remains reasonably simple.

Another solution would be to modify the interface to specify the rates of
the various pieces of information separately; it'd then set the timer to
be some approximation of the gcd, and only provide a given piece of data
every k calls to onstats.

**Comment by ineol** [comment]
>  Another solution would be to modify the interface to specify the rates of the various pieces of information separately; it'd then set the timer to be some approximation of the gcd, and only provide a given piece of data every k calls to onstats.

The new version basically does this, but instead of gcd, it keeps track of the two intervals and deadlines and sleeps accordingly.

**Comment by jech** [comment]
This seems like a somewhat ad-hoc solution.  Any ideas for a more generic API?

**Comment by ineol** [comment]
The public API seems reasonable to me, you have an `onblah` callback called with an interval set by `setBlahInterval()` with the relevant info. Which part do you find ad-hoc?

**Pull request closed without merging**
