### PR TITLE
changes for keyboard and scrennreader users

### PR DESCRIPTION
**Pull request by jjsarton**

### CODE REVIEW

**Comment by jech** [comment]
This patch appears to do three unrelated things.  Perhaps you could split it into three patches?  (As a side note, it's easy to squash patches, but difficult to split them.  Perhaps you shold get into the habit of committing more often?)

1. Replacing `<div>` with `<button>`

  I fully agree, that's a good thing.  I'll apply it as soon as you've split it out.

2. Keyboard shortcuts

   The intent is that people with disabilities can use slash commands in the chat rather than interacting with the UI.  So instead of adding keyboard shortcuts, which are difficult to memorise and interact badly with people's environments (people with screen readers already have a number of commands to control the screen reader, and we should not interfere with that), we should focus on adding more /commands.

3. Adding `<h1>` and friends

  If the intent is to make keyboard navigation easier, then please see the previous point.  If the intent is something else, then please explain (the git commit message is the best place to do that, since git commit messages remain in the repository and are easy to find using `git blame`).

**Comment by jjsarton** [comment]
>     1. Replacing `<div>` with `<button>`
>        I fully agree, that's a good thing.  I'll apply it as soon as you've split it out.
For one element, I was not able to replace it with a button. This is handled within the script key.js.

>     2. Keyboard shortcuts
>        The intent is that people with disabilities can use slash commands in the chat rather than interacting with the UI.  So instead of adding keyboard shortcuts, which are difficult to memorise and interact badly with people's environments (people with screen readers already have a number of commands to control the screen reader, and we should not interfere with that), we should focus on adding more /commands.

The problem is to select the user list, the chatbox or the video area. If I use the tabulator I may have to issue a lot of tabs.
This is not very nice. For this we need only 3 keys (u, c and  v which is not assigned, firefox and chromium have different behaviour.
I can delete mute and raise/unraise.
These shortcuts are not intended for screenreader user.
> 
>     3. Adding `<h1>` and friends
>        If the intent is to make keyboard navigation easier, then please see the previous point.  If the intent is something else, then please explain (the git commit message is the best place to do that, since git commit messages remain in the repository and are easy to find using `git blame`).

H1 and friends are only for screenreader user, this is offered by all screenreader ons desktop systems as well as smartphone, but this is for such touch system not so good (choose the wanted action for navigation: rotor for iPhone, and iPad, Android  talkback (I don't know the english term) has also a similar function).

**Comment by jjsarton** [comment]
I don't think that the patch do unrelated thinks.
Keyboard navigation is usefull for user without mouse, the patch consider the needs for user which can use a mouse due to visual impairement (screenreader user) and user with motor disability.

**Comment by jech** [comment]
I'm sorry, but you need to split the patch.

**Pull request closed without merging**
