### PR TITLE
Make login box height automatic

### PR DESCRIPTION
**Pull request by erdnaxe**
Do not hardcore login box height so its height can change depending on the content. Using "margin: auto" garantee that the box will be vertically and horizontally centered.

I have seen some instances of Galène where the admin changed the content of the login box. This patch makes the login box look great when content is added or removed inside.

### CODE REVIEW

**Comment by jech** [comment]
@takdj?

**Comment by takdj** [comment]
I really don't like the box centered like that, it do not looks good.

automatic height can be done, in case elements are added or remove in login box.

**Comment by erdnaxe** [comment]
Oh ok I did not know that was intentional. I updated the commit with only the height removed, is this better?

**Comment by takdj** [comment]
There is blank space bellow `Connect` button. You can see in this image

Screenshot 2021-04-27 14 36 22

**Comment by jech** [comment]
Closing due to @takdj's opposition.  Please reopen if you disagree, or create a new pull request.

**Pull request closed without merging**
